name: Pre-commit Checks

on: 
  pull_request:
    paths:
      - "tuning/*"

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Change to `tuning` directory
        run: cd tuning

      - name: Run lint test
      working-directory: tuning
      uses: pre-commit/action@v3.0.1
                
      - name: Run pytest
        working-directory: tuning
        run: |
          pytest -m test_autotune.py
          pytest -m test_tune.py
